# Generated by Django 3.2.7 on 2021-09-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_price_listing_start_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-price']},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='img',
            new_name='image',
        ),
    ]
