# Generated by Django 3.2.7 on 2021-09-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_description_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home'), ('farming', 'Farming'), ('sports', 'Sports')], max_length=64),
        ),
    ]
