# Generated by Django 3.2.7 on 2021-09-06 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('arts', 'Arts'), ('electronics', 'Electronics'), ('farming', 'Farming'), ('fashion', 'Fashion'), ('home', 'Home'), ('sports', 'Sports'), ('toys', 'Toys')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won', to=settings.AUTH_USER_MODEL),
        ),
    ]
